openapi: 3.0.3
info:
  title: Swagger FoodProvider REST - OpenAPI 3.0
  description: |-
    Servizio per la gestione dei FoodProvider.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of SpeseManager, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_
    
  termsOfService: http://swagger.io/terms/
  contact:
    email: enrico.trx@hotmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/OrdiniServ/
tags:
  - name: provider
    description: Tutto riguardo i tuoi food provider
paths:
  /provider:
  
    get:
      tags:
        - provider
      summary: Ottieni i provider esistenti
      description: Ottieni i provider esistenti
      operationId: elencoProvider
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provider'    
            application/xml:
              schema:
                $ref: '#/components/schemas/Provider'
        '404':
          description: Ordini non trovati
        '500':
          description: Internal Server Error
          
    post:
      tags:
        - provider
      summary: Aggiungi un nuovo provider
      description: Aggiungi un nuovo provider
      operationId: creaProvider
      requestBody:
        description: Crea un nuovo provider
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/Provider'
          application/xml:
              schema:
                $ref: '#/components/schemas/Provider'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Provider'
        required: true
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provider'  
            application/xml:
              schema:
                $ref: '#/components/schemas/Provider'
        '405':
          description: Input non valido
  
  /provider/{categoria}:
    get:
      tags:
        - provider
      summary: Trova i provider in base alla categoria
      description: Ritorna una lista di provider
      operationId: getProvider
      parameters:
        - name: categoria
          in: path
          description: ID della categoria di food provider
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provider'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Provider'
        '400':
          description: ID fornito non valido
        '404':
          description: Provider non trovato
    
  /provider/{id}:
    get:
      tags:
        - provider
      summary: Trova il provider in base all'id
      description: Ritorna un singolo provider
      operationId: getProvider
      parameters:
        - name: id
          in: path
          description: ID del food provider
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provider'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Provider'
        '400':
          description: ID fornito non valido
        '404':
          description: Provider non trovato
    
    put:
      tags:
        - provider
      summary: Update di un provider esistente
      description: Update di un provider esistente dato l'Id
      operationId: aggiornaProvider
      parameters:
        - name: id
          in: path
          description: ID del provider che si vuole aggiornare
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update di un provider esistente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Provider'
          application/xml:
            schema:
              $ref: '#/components/schemas/Provider'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Provider'
        required: true
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provider'        
            application/xml:
              schema:
                $ref: '#/components/schemas/Provider'
        '400':
          description: ID fornito non valido
        '404':
          description: Provider non trovato
        '405':
          description: Errore di validazione
            
    delete:
      tags:
        - provider
      summary: Cancella un provider
      description: cancella un provider dato l'id
      operationId: cancellaProvider
      parameters:
        - name: api_key
          in: header
          description: cancella un provider 
          required: false
          schema:
            type: int
        - name: id
          in: path
          description: ID del provider da eliminare
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operazione riuscita!
        '400':
          description: ID fornito non valido
        '404':
          description: Provider non trovato!
        

components:
  schemas:

    Provider:
      required:
        - id_food_provider
      type: object
      properties:
        id_food_provider:
          type: integer
          format: int64
          example: 2
        id_categoria_food_provider:
          type: integer
          format: int64
          example: 4
        id_profilo:
          type: integer
          format: int64
          example: 6
        partita_iva:
          type: string
          example: "akvmrknf34"
        nome_food_provider:
          type: string
          example: "MrRonald's"
        prezzo consegna:
          type: double
          example: 8.0
        ordine minimo:
          type: double
          example: 10.0
        orario_food_provider:
          type: string
          example: "12:00-22:30"
        

    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Utente:
          description: oggetto Provider da aggiungere al registro
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Provider'
        application/xml:
          schema:
            $ref: '#/components/schemas/Provider'