openapi: 3.0.3
info:
  title: Swagger Ingredienti REST - OpenAPI 3.0
  description: |-
    Servizio per la gestione degli ingredienti.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of SpeseManager, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_
    
  termsOfService: http://swagger.io/terms/
  contact:
    email: enrico.trx@hotmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/IngredientiServ/
tags:
  - name: ingrediente
    description: Tutto riguardo i tuoi ingredienti
paths:
  /ingrediente:
  
    get:
      tags:
        - ingrediente
      summary: Ottieni i ingredienti esistenti
      description: Ottieni i ingredienti esistenti
      operationId: elencoIngredienti
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingrediente'    
            application/xml:
              schema:
                $ref: '#/components/schemas/Ingrediente'
        '404':
          description: Ingredienti non trovati
        '500':
          description: Internal Server Error
          
    post:
      tags:
        - ingrediente
      summary: Aggiungi un nuovo ingrediente
      description: Aggiungi un nuovo ingrediente
      operationId: creaIngrediente
      requestBody:
        description: Crea un nuovo ingrediente
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/Ingrediente'    
          application/xml:
              schema:
                $ref: '#/components/schemas/Ingrediente'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Ingrediente'
        required: true
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingrediente'        
            application/xml:
              schema:
                $ref: '#/components/schemas/Ingrediente'
        '405':
          description: Input non valido
            
  /ingrediente/{id}:
    get:
      tags:
        - ingrdiente
      summary: Trova ingrediente dall'ID (hashed)
      description: Ritorna un singolo ingrediente
      operationId: getIngrediente
      parameters:
        - name: id
          in: path
          description: ID dell' ingrediente da ritornare
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingrediente'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Ingrediente'
        '400':
          description: ID fornito non valido
        '404':
          description: Ingrediente non trovato
    put:
      tags:
        - ingrediente
      summary: Update di una ingrediente esistente
      description: Update di un ingrediente esistente dato l'Id
      operationId: aggiornaIngrediente
      requestBody:
        description: Update di un ingrediente esistente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ingrediente'
          application/xml:
            schema:
              $ref: '#/components/schemas/Ingrediente'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Ingrediente'
        required: true
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingrediente'        
            application/xml:
              schema:
                $ref: '#/components/schemas/Ingrediente'
        '400':
          description: ID fornito non valido
        '404':
          description: Ingrediente non trovata
        '405':
          description: Errore di validazione
            
    delete:
      tags:
        - ingrediente
      summary: Cancella un'ingrediente
      description: cancella un'ingrediente dato l'id
      operationId: cancellaIngrediente
      parameters:
        - name: api_key
          in: header
          description: ''
          required: false
          schema:
            type: string
        - name: id
          in: path
          description: ID dell'ingrediente da eliminare
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operazione riuscita!
        '400':
          description: ID fornito non valido
        '404':
          description: Ingrediente non trovato!
        
components:
  schemas:

    Ingrediente:
      required:
        - nome
      type: object
      properties:
        id_ingrediente:
          type: integer
          format: int64
          example: 10
        nome:
          type: string
          example: 'pomodoro'
        prezzo:
          type: decimal
          example: 2.70
         
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Ingrediente:
      description: oggetto Ingrediente da aggiungere al registro
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Ingrediente'
        application/xml:
          schema:
            $ref: '#/components/schemas/Ingrediente'