openapi: 3.0.3
info:
  title: Swagger Recensioni REST - OpenAPI 3.0
  description: |-
    Servizio per la gestione delle Recensioni.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of SpeseManager, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_
    
  termsOfService: http://swagger.io/terms/
  contact:
    email: enrico.trx@hotmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/RecensioniServ/
tags:
  - name: recensione
    description: Tutto riguardo le tue recensioni
paths:
  /recensioni:
  
    get:
      tags:
        - recensione
      summary: Ottieni le recensioni esistenti
      description: Ottieni le recensioni esistenti
      operationId: elencoRecensioni
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recensione'    
            application/xml:
              schema:
                $ref: '#/components/schemas/Recensione'
        '404':
          description: Ordini non trovati
        '500':
          description: Internal Server Error
          
    post:
      tags:
        - recensione
      summary: Aggiungi una nuova recensione
      description: Aggiungi una nuova recensione
      operationId: creaRecensione
      requestBody:
        description: Crea un nuovo recensione
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/Recensione'
          application/xml:
              schema:
                $ref: '#/components/schemas/Recensione'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Recensione'
        required: true
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recensione'
            application/xml:
              schema:
                $ref: '#/components/schemas/Recensione'
        '405':
          description: Input non valido
  
  /recensioni/{ordine}:
    get:
      tags:
        - recensione
      summary: Trova le recensioni in base all'ordine
      description: Ritorna una lista di recensioni
      operationId: getRecensioni
      parameters:
        - name: ordine
          in: path
          description: ID dell'ordine
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recensione'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Recensione'
        '400':
          description: ID fornito non valido
        '404':
          description: Recensione non trovata
    
  /recensioni/{id}:
    get:
      tags:
        - recensione
      summary: Trova una recensione in base all'id
      description: Ritorna una singola recensione
      operationId: getRecensione
      parameters:
        - name: id
          in: path
          description: ID della recensione
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recensione'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Recensione'
        '400':
          description: ID fornito non valido
        '404':
          description: Recensione non trovato
    
    put:
      tags:
        - recensione
      summary: Update di una recensione esistente
      description: Update di una recensione esistente dato l'Id
      operationId: aggiornaRecensione
      parameters:
        - name: id
          in: path
          description: ID della recensione che si vuole aggiornare
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update di una recensione esistente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recensione'
          application/xml:
            schema:
              $ref: '#/components/schemas/Recensione'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Recensione'
        required: true
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recensione'        
            application/xml:
              schema:
                $ref: '#/components/schemas/Recensione'
        '400':
          description: ID fornito non valido
        '404':
          description: Recensione non trovato
        '405':
          description: Errore di validazione
            
    delete:
      tags:
        - recensione
      summary: Cancella una recensione
      description: cancella una recensione dato l'id
      operationId: cancellaRecensione
      parameters:
        - name: api_key
          in: header
          description: cancella una recensione
          required: false
          schema:
            type: int
        - name: id
          in: path
          description: ID della recensione da eliminare
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operazione riuscita!
        '400':
          description: ID fornito non valido
        '404':
          description: Recensione non trovato!
        

components:
  schemas:

    Recensione:
      required:
        - id_recensione
      type: object
      properties:
        id_recensione:
          type: integer
          format: int64
          example: 2
        id_ordine:
          type: integer
          format: int64
          example: 4
        titolo:
          type: string
          example: "Ottima pizza!"
        orario_recensione:
          type: time
          example: '21:30'
        numero_stelle:
          type: double
          format: int64
          example: 4.5
        descrizione:
          type: string
          example: "Pizza molto buona solo un po' pesante."
        

    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Utente:
          description: oggetto Recensione da aggiungere al registro
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Recensione'
        application/xml:
          schema:
            $ref: '#/components/schemas/Recensione'