openapi: 3.0.3
info:
  title: Swagger Ruoli REST - OpenAPI 3.0
  description: |-
    Servizio per la gestione dei ruoli.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of SpeseManager, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_
    
  termsOfService: http://swagger.io/terms/
  contact:
    email: enrico.trx@hotmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/RuoliServ/
tags:
  - ruolo: utente
    description: Tutto riguardo i tuoi ruoli
paths:
  /ruolo:
  
    get:
      tags:
        - ruolo
      summary: Ottieni i ruoli esistenti
      description: Ottieni i ruoli esistenti
      operationId: elencoRuoli
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ruolo'    
            application/xml:
              schema:
                $ref: '#/components/schemas/Ruolo'
        '404':
          description: Ruoli non trovati
        '500':
          description: Internal Server Error
          
    post:
      tags:
        - ruolo
      summary: Aggiungi un nuovo ruolo
      description: Aggiungi un nuovo ruolo
      operationId: creaRuolo
      requestBody:
        description: Crea un nuovo ruolo
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/Ruolo'    
          application/xml:
              schema:
                $ref: '#/components/schemas/Ruolo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Ruolo'
        required: true
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ruolo'        
            application/xml:
              schema:
                $ref: '#/components/schemas/Ruolo'
        '405':
          description: Input non valido
            
  /ruolo/{id}:
    get:
      tags:
        - ruolo
      summary: Trova ruolo dall'ID (hashed)
      description: Ritorna un singolo ruolo
      operationId: getRuolo
      parameters:
        - name: id
          in: path
          description: ID del ruolo da ritornare
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ruolo'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Ruolo'
        '400':
          description: ID fornito non valido
        '404':
          description: Ruolo non trovato
        
components:
  schemas:

    Ruolo:
      required:
        - ruolo
        - descrizione
      type: object
      properties:
        id_ruolo:
          type: integer
          format: int64
          example: 10
        ruolo:
          type: string
          example: 'fattorino'
        descrizione:
          type: string
          example: 'consegna i prodotti ordinati'
        
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Ruolo:
      description: oggetto Ruolo da aggiungere al registro
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Ruolo'
        application/xml:
          schema:
            $ref: '#/components/schemas/Ruolo'