openapi: 3.0.3
info:
  title: Swagger Utenti REST - OpenAPI 3.0
  description: |-
    Servizio per la gestione degli utenti.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of SpeseManager, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_
    
  termsOfService: http://swagger.io/terms/
  contact:
    email: enrico.trx@hotmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/UtentiServ/
tags:
  - name: utente
    description: Tutto riguardo i tuoi utenti
paths:
  /utente:
  
    get:
      tags:
        - utente
      summary: Ottieni gli utenti esistenti
      description: Ottieni gli utenti esistenti
      operationId: elencoUtenti
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utente'    
            application/xml:
              schema:
                $ref: '#/components/schemas/Utente'
        '404':
          description: Utenti non trovati
        '500':
          description: Internal Server Error
          
    post:
      tags:
        - utente
      summary: Aggiungi un nuovo utente
      description: Aggiungi un nuovo utente
      operationId: creaUtente
      requestBody:
        description: Crea un nuovo utente
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/Utente'    
          application/xml:
              schema:
                $ref: '#/components/schemas/Utente'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Utente'
        required: true
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utente'        
            application/xml:
              schema:
                $ref: '#/components/schemas/Utente'
        '405':
          description: Input non valido
          
  /utente/login:
    get:
      tags:
        - utente
      summary: Trova l'utente cercato
      description: Trova l'utente cercato in base a email e password
      operationId: getUtente
      parameteters:
        - in: path
          name: email
          required: true
          schema:
            type: string
        - in: path
          name: password
          required: true
          schema:
            type: string
  
  /utente/{id}:
    get:
      tags:
        - utente
      summary: Trova utente dall'ID (hashed)
      description: Ritorna un singolo utente
      operationId: getUtente
      parameters:
        - name: id
          in: path
          description: ID dell'utente da ritornare
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utente'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Utente'
        '400':
          description: ID fornito non valido
        '404':
          description: Utente non trovato
    put:
      tags:
        - utente
      summary: Update di una utente esistente
      description: Update di un'utente esistente dato l'Id
      operationId: aggiornaUtente
      requestBody:
        description: Update di un'utente esistente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Utente'
          application/xml:
            schema:
              $ref: '#/components/schemas/Utente'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Utente'
        required: true
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utente'        
            application/xml:
              schema:
                $ref: '#/components/schemas/Utente'
        '400':
          description: ID fornito non valido
        '404':
          description: Utente non trovato
        '405':
          description: Errore di validazione
            
    delete:
      tags:
        - utente
      summary: Cancella un'utente
      description: cancella un'utente dato l'id
      operationId: cancellaUtente
      parameters:
        - name: api_key
          in: header
          description: ''
          required: false
          schema:
            type: string
        - name: id
          in: path
          description: ID dell'utente da eliminare
          required: true
          schema:
            type: integer
            format: int64
        - name: password
          in: path
          description: string
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operazione riuscita!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UtenteId'          
            application/xml:
              schema:
                $ref: '#/components/schemas/UtenteId'
        '400':
          description: ID fornito non valido
        '404':
          description: Utente non trovato!
        
components:
  schemas:

    Utente:
      required:
        - email
      type: object
      properties:
        id_utente:
          type: integer
          format: int64
          example: 10
        email:
          type: string
          example: 'nome.cognome@mail.com'
      
    PassMail:
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
          example: 'nome.cognome@mail.com'
        password:
          type: string
          example: 'Password_1'
      
    UtenteId:
      required:
        - id_utente
      type: object
      properties:
        id_utente:
          type: integer
          format: int64
          example: 10
         
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Utente:
      description: oggetto Utente da aggiungere al registro
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Utente'
        application/xml:
          schema:
            $ref: '#/components/schemas/Utente'